### PR TITLE
Add basic Travis CI config and setup script

### PR DESCRIPTION
**Pull request by arjunmehta**
This PR has basic config for OSX and Linux on Travis CI. Addresses unbornchikken/NOOOCL#24

OSX has OpenCL by default. Travis uses Ubuntu, and requires the (somewhat painful) installation of the Intel OpenCL drivers. Basic method replicated from [cdeterman/intel_opencl](https://github.com/cdeterman/intel_opencl).

The setup script may need to be modified to fix any driver installation issues that may or may not be present.

Works, but reveals failures on both OSX and Ubuntu. This should help with future troubleshooting.

### CODE REVIEW

**Comment by arjunmehta** [comment]
@unbornchikken It could use some clean up.
Let me know If you think this is mergeable. I tested this on my fork and it sets up and replicates the issues I was having on OSX, so... it seems like it works! Ubuntu is running well too, but also perhaps revealing driver issues.

I can try and clean out some unused bits. I think I've included compilers in the travis.yml file that are unused.

**Comment by arjunmehta** [comment]
@unbornchikken It could use some clean up.
Let me know If you think this is mergeable. I tested this on my fork and it sets up and replicates the issues I was having on OSX, so... it seems like it works! Ubuntu is running well too, but also perhaps revealing driver issues.

I can try and clean out some unused bits. I think I've included compilers in the travis.yml file that are unused.

**Comment by arjunmehta** [comment]
Just realizing, compiler may not even be needed in either environments. I will need to test. The Intel drivers probably shouldn't need it, but I never know with Linux.

There is nothing in NOOOCL that requires a compiler yeah? It's all handled by cmake-js?

**Comment by unbornchikken** [comment]
It's all handled by CMake.js, however CMake.js uses C++ build tools and CMake of course to build native modules. See the requirements there: https://github.com/cmake-js/cmake-js#installation

**Comment by unbornchikken** [comment]
For side not, I'm developing NOOOCL on Ubuntu with NVidia (my laptop) and on Win10/i5 with AMD R9 (my desktop). So it should work on those platforms with proper setup for sure.

**Comment by arjunmehta** [comment]
@unbornchikken Yeah I wish travis had Nvidia and AMD GPU systems to test. And also windows environments.

I was able to remove all the compiler references from the travis config. Ubuntu comes with gcc I think. You can see how it runs here: https://travis-ci.org/arjunmehta/NOOOCL/builds/184273080

**Comment by arjunmehta** [comment]
Sorry for the messy PR. You probably want to [squash and merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits)

**Comment by unbornchikken** [comment]
Does it do a successful build and test? The last one you linked shows there is no device found, which means OpenCL is not working entirely.

**Comment by arjunmehta** [comment]
It is doing a successful build (I believe), and runs the tests (only using CPU of course). But fails in both test cases:

**Linux Output:**
```
  CLBuffer
GPU is not available!
    ✓ can copy contents of two node.js buffer through OpenCL (266ms)
    ✓ supports sub buffers (206ms)
    ✓ supports mapping of host array (186ms)
  CLContext
    ✓ should construct from a device (204ms)
    ✓ should construct from type (186ms)
  CLHost
    ✓ should return platforms and devices (39ms)
  CLImage2D
    ✓ should convert an image to grayscale (364ms)
  CLKernel
    ✓ should enqueue NDRange kernels (216ms)
  CLContext
    ✓ should build and get kernel from string source (199ms)
    ✓ should fail by building a fucked up string source (245ms)
    ✓ should support binaries (206ms)
  NOOOCL
    1) should call release on out of scope
    2) should call release on GC
  11 passing (3s)
  2 failing
```

**OSX Output:**
```
  CLBuffer
GPU is not available!
    ✓ can copy contents of two node.js buffer through OpenCL (122ms)
    ✓ supports sub buffers (67ms)
    ✓ supports mapping of host array
  CLContext
    ✓ should construct from a device (47ms)
    ✓ should construct from type (39ms)
  CLHost
    ✓ should return platforms and devices (51ms)
  CLImage2D
/Users/travis/build.sh: line 57:  1916 Illegal instruction: 4  npm test
The command "npm test" exited with 132.
```

**Comment by unbornchikken** [comment]
Before merging this, please try it with the latest version that I've just released. OSX should work, and tests should run on CPU first.

**Comment by arjunmehta** [comment]
I rebased, and it works! Beautifully.
However the commit history went nuts. Please ensure the changes you made are retained!

**Comment by arjunmehta** [comment]
Hmm looks like the test is still failing on Ubuntu: https://travis-ci.org/arjunmehta/NOOOCL/jobs/185208995

Do you think it has something to do with the environment?

**Comment by arjunmehta** [comment]
@unbornchikken It looks like the tests in NOOOCL/test/testObjectLifetime.js are gpu specific. This is probably why they are failing on Travis. Is there any way to make them cpu or gpu agnostic?
Specifically at [L31](https://github.com/unbornchikken/NOOOCL/blob/master/test/testObjectLifetime.js#L31) and [L63](https://github.com/unbornchikken/NOOOCL/blob/master/test/testObjectLifetime.js#L63)?

**Comment by unbornchikken** [comment]
On. Thx.

**Pull request merged**
